version: '3.8'

services:
  server:
    build: .
    ports:
      - "8080:8080"
      - "1234:1234"
    environment:
      - HTTP_PORT=8080
      - RPC_PORT=1234
      - FILE_URL=https://s3.g.s4.mega.io/2cnjyiqqebttwjrnbitzpvy6uw4j7ujo4bxnu/jiahua-bucket/test.txt
      - CHUNK_SIZE=500000
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8080/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    name: word-counter-network