version: '3.3'

services:
  word-counter-worker:
    build: .
    environment:
      - WORKER_ID=worker-${HOSTNAME:-${RANDOM}}
      - RPC_SERVER_ADDR=${RPC_SERVER_ADDR:-98.82.151.62:1234}
      - REPORT_BACK_URL=${REPORT_BACK_URL:-http://98.82.151.62:8080/results}
      - POLL_INTERVAL=${POLL_INTERVAL:-5s}
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'

# Simple scaling: docker-compose up --scale word-counter-worker=N